language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=^3.7 PHPUNIT_VERSION=^7.0
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=^3.7 PHPUNIT_VERSION=^7.0

sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - if [ -n "$ILLUMINATE_VERSION" ] ; then composer require illuminate/support:${ILLUMINATE_VERSION} illuminate/validation:${ILLUMINATE_VERSION} --no-update; fi
  - if [ -n "$TESTBENCH_VERSION" ] ; then composer require orchestra/testbench:${TESTBENCH_VERSION} --no-update; fi
  - if [ -n "$PHPUNIT_VERSION" ] ; then composer require phpunit/phpunit:${PHPUNIT_VERSION} --no-update; fi

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - ./vendor/bin/phpunit --verbose
