language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  - ILLUMINATE_VERSION=5.0.* TESTBENCH_VERSION=^3.0 PHPUNIT_VERSION=^4.0
  - ILLUMINATE_VERSION=5.1.* TESTBENCH_VERSION=^3.1 PHPUNIT_VERSION=^5.0
  - ILLUMINATE_VERSION=5.2.* TESTBENCH_VERSION=^3.2 PHPUNIT_VERSION=^5.0
  - ILLUMINATE_VERSION=5.3.* TESTBENCH_VERSION=^3.3 PHPUNIT_VERSION=^5.0
  - ILLUMINATE_VERSION=5.4.* TESTBENCH_VERSION=^3.4 PHPUNIT_VERSION=^5.0
  - ILLUMINATE_VERSION=5.5.* TESTBENCH_VERSION=^3.5 PHPUNIT_VERSION=^6.0
  - ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=^3.6 PHPUNIT_VERSION=^7.0
  - ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=^3.7 PHPUNIT_VERSION=^7.0

matrix:
  exclude: # Laravel 5.6 & 5.7 do not support PHP7.0
    - php: 7.0
      env: ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=^3.6 PHPUNIT_VERSION=^7.0
    - php: 7.0
      env: ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=^3.7 PHPUNIT_VERSION=^7.0
  allow_failures:
    - php: nightly

sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - if [ -n "$ILLUMINATE_VERSION" ] ; then composer require illuminate/support:${ILLUMINATE_VERSION} illuminate/validation:${ILLUMINATE_VERSION} --no-update; fi
  - if [ -n "$TESTBENCH_VERSION" ] ; then composer require orchestra/testbench:${TESTBENCH_VERSION} --no-update; fi
  - if [ -n "$PHPUNIT_VERSION" ] ; then composer require phpunit/phpunit:${PHPUNIT_VERSION} --no-update; fi

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - ./vendor/bin/phpunit --verbose
